version: '3'
services:
  db:
    image: 'mongo'
    networks:
      - i18n_management_network
  api:
    build:
      dockerfile: Dockerfile
    volumes:
      - /app
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - i18n_management_network
networks:
  i18n_management_network:
    driver: bridge
